### ISSUE TITLE
State license of modules in nektsrs derived from pymech

### ISSUE THREAD

**Issue by ashwinvis** [timofeymukha/nektsrs#1]
First off all good work.As I went through the code, it appeared to me that some functions which read (and perhaps also write Nek5000 field files) were derived from GPL licensed pymech (perhaps via KTH toolbox, where in a comment it is stated that it was based on pymech).

It os fine to keep the package under MIT as it is now. But the modules in question shouöd contain the GPL license notice 

https://www.gnu.org/licenses/gpl-faq.en.html#GPLModuleLicense

**Comment by timofeymukha** [comment]
Hi! Like this? I just took stuff from the tsrs example in the toolbox
https://github.com/timofeymukha/nektsrs/blob/master/nektsrs/io/helpers.py

**Comment by ashwinvis** [comment]
Yes, if that is the only module. Perhaps header, time_series, writer too. Also add a copyright notice on top

Copyright 2022 eX-Mech/pymech developers

As suggested here https://www.gnu.org/licenses/gpl-howto.html

Thanks
Ashwin

Sent from Proton Mail mobile

-------- Original Message --------
